CREATE TABLE IF NOT EXISTS Cliente (
 cpf CHAR(11) NOT NULL,
 nome VARCHAR(200) NOT NULL,
 idade INT NOT NULL,
 genero BOOLEAN NOT NULL,
 socio BOOLEAN DEFAULT FALSE NOT NULL,
 numsocio VARCHAR(20)
);

ALTER TABLE Cliente ADD CONSTRAINT PK_Cliente PRIMARY KEY (cpf);

CREATE TABLE IF NOT EXISTS Bar (
 cliente_cpf CHAR(11) NOT NULL
);

ALTER TABLE Bar ADD CONSTRAINT PK_Bar_Cliente PRIMARY KEY (cliente_cpf);
ALTER TABLE Bar ADD CONSTRAINT FK_Cliente FOREIGN KEY (cliente_cpf) REFERENCES Cliente (cpf);


